- name: Add a new user and configure SSH key
  hosts: all
  become: true
  tasks:
    - name: Create a new user
      user:
        name: anush
        state: present
        shell: /bin/bash
        create_home: yes

    - name: Create SSH directory for the new user
      file:
        path: "/home/anush/.ssh"
        state: directory
        owner: anush
        group: anush
        mode: '0700'

    - name: Copy SSH public key to the new user's authorized_keys
      copy:
        content: "{{ lookup('file', '~/.ssh/ansible1_key.pub') }}"
        dest: "/home/anush/.ssh/authorized_keys"
        owner: anush
        group: anush
        mode: '0600'
 
